version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:cakcuk33@db/erasmus_contracts
      - SECRET_KEY=your-secret-key-for-jwt-tokens
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - UPLOAD_FOLDER=./uploads
      - TEMPLATES_FOLDER=./templates
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cakcuk33
      - POSTGRES_DB=erasmus_contracts
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: